USE ROLE TRAINING_ROLE;
USE WAREHOUSE FERRET_QUERY_WH;
USE SCHEMA RAW;
USE DATABASE USER_DB_FERRET;

CREATE SCHEMA IF NOT EXISTS ADHOC;

CREATE OR REPLACE TABLE CITY_WEATHER (
    CITY STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    DATE DATE,
    TEMP_MAX FLOAT,
    TEMP_MIN FLOAT,
    TEMP_MEAN FLOAT,
    PRECIPITATION_MM FLOAT,
    WIND_SPEED_MAX_KMH FLOAT,
    WEATHER_CODE INTEGER,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (CITY, DATE)
);

DESC TABLE RAW.CITY_WEATHER;

SELECT * FROM RAW.CITY_WEATHER;

SELECT COUNT(*) FROM RAW.CITY_WEATHER;

SELECT city, COUNT(*)
FROM RAW.CITY_WEATHER
GROUP BY city;

SELECT * 
FROM ADHOC.CITY_WEATHER_FORECAST;

SELECT *
FROM ANALYTICS.CITY_WEATHER_FINAL
ORDER BY CITY, DATE DESC;


SELECT 
    CITY,
    MIN(DATE) AS first_date,
    MAX(DATE) AS last_date,
    COUNT(*) AS total_records
FROM RAW.CITY_WEATHER
GROUP BY CITY;

SELECT
CITY,
DATE,
TEMP_MAX,
TEMP_MIN,
TEMP_MEAN,
PRECIPITATION_MM,
WIND_SPEED_MAX_KMH,
WEATHER_CODE,
    CASE WEATHER_CODE
    WHEN 0 THEN 'Clear sky'
    WHEN 1 THEN 'Mainly clear'
    WHEN 2 THEN 'Partly cloudy'
    WHEN 3 THEN 'Overcast'
    WHEN 45 THEN 'Fog'
    WHEN 48 THEN 'Rime fog'
    WHEN 51 THEN 'Light drizzle'
    WHEN 53 THEN 'Moderate drizzle'
    WHEN 55 THEN 'Dense drizzle'
    WHEN 61 THEN 'Slight rain'
    WHEN 63 THEN 'Moderate rain'
    WHEN 65 THEN 'Heavy rain'
    WHEN 71 THEN 'Slight snow'
    WHEN 73 THEN 'Moderate snow'
    WHEN 75 THEN 'Heavy snow'
    WHEN 80 THEN 'Rain showers'
    WHEN 81 THEN 'Moderate rain showers'
    WHEN 82 THEN 'Violent rain showers'
    WHEN 95 THEN 'Thunderstorm'
    WHEN 96 THEN 'Thunderstorm with hail'
    WHEN 99 THEN 'Severe thunderstorm'
    ELSE 'Unknown'
    END AS WEATHER_DESCRIPTION
FROM RAW.CITY_WEATHER
ORDER BY CITY, DATE DESC;


SELECT
CITY,
DATE,
TEMP_MAX,
TEMP_MIN,
TEMP_MEAN,
PRECIPITATION_MM,
WIND_SPEED_MAX_KMH,
WEATHER_CODE
FROM RAW.CITY_WEATHER
WHERE CITY = 'Newport Beach'
ORDER BY DATE DESC
LIMIT 5;


SELECT CITY, DATE, COUNT(*)
FROM RAW.CITY_WEATHER
GROUP BY CITY, DATE
HAVING COUNT(*) > 1;















