/* ============================================================================
   Weather Data Analytics – Snowflake SQL Script
   Purpose: Environment setup, table creation, data validation, and exploration
   for the Weather ETL + Forecasting pipeline.
   ============================================================================ */

-- ---------------------------------------------------------------------------
-- 1. Set Snowflake context (role, warehouse, database, schema)
-- ---------------------------------------------------------------------------
USE ROLE TRAINING_ROLE;
USE WAREHOUSE FERRET_QUERY_WH;
USE DATABASE USER_DB_FERRET;
USE SCHEMA RAW;

-- Create ADHOC schema for temporary analysis, ML outputs, and forecast tables
CREATE SCHEMA IF NOT EXISTS ADHOC;

-- ---------------------------------------------------------------------------
-- 2. Create RAW.CITY_WEATHER table (historical weather data)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TABLE CITY_WEATHER (
    CITY STRING,                     -- City name
    LATITUDE FLOAT,                  -- Latitude of the city
    LONGITUDE FLOAT,                 -- Longitude of the city
    DATE DATE,                       -- Observation date
    TEMP_MAX FLOAT,                  -- Max temperature
    TEMP_MIN FLOAT,                  -- Min temperature
    TEMP_MEAN FLOAT,                 -- Mean temperature
    PRECIPITATION_MM FLOAT,          -- Precipitation in mm
    WIND_SPEED_MAX_KMH FLOAT,        -- Max wind speed (km/h)
    WEATHER_CODE INTEGER,            -- Weather condition code
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), -- Ingestion timestamp

    PRIMARY KEY (CITY, DATE)         -- Prevent duplicate daily records per city
);

-- ---------------------------------------------------------------------------
-- 3. Table structure and basic data checks
-- ---------------------------------------------------------------------------

-- View table metadata
DESC TABLE RAW.CITY_WEATHER;

-- Preview all data
SELECT * FROM RAW.CITY_WEATHER;

-- Count total records
SELECT COUNT(*) FROM RAW.CITY_WEATHER;

-- Count records per city
SELECT city, COUNT(*)
FROM RAW.CITY_WEATHER
GROUP BY city;

-- ---------------------------------------------------------------------------
-- 4. Forecast and final dataset checks
-- ---------------------------------------------------------------------------

-- View forecasted weather data (generated by ML pipeline)
SELECT * FROM ADHOC.CITY_WEATHER_FORECAST;

-- View final combined dataset (historical + forecast)
SELECT *
FROM ANALYTICS.CITY_WEATHER_FINAL
ORDER BY CITY, DATE DESC;

-- ---------------------------------------------------------------------------
-- 5. Validate date ranges and completeness per city
-- ---------------------------------------------------------------------------
SELECT 
    CITY,
    MIN(DATE) AS first_date,
    MAX(DATE) AS last_date,
    COUNT(*) AS total_records
FROM RAW.CITY_WEATHER
GROUP BY CITY;

-- ---------------------------------------------------------------------------
-- 6. Weather code → human-readable description mapping
-- ---------------------------------------------------------------------------
SELECT
    CITY,
    DATE,
    TEMP_MAX,
    TEMP_MIN,
    TEMP_MEAN,
    PRECIPITATION_MM,
    WIND_SPEED_MAX_KMH,
    WEATHER_CODE,
    CASE WEATHER_CODE
        WHEN 0 THEN 'Clear sky'
        WHEN 1 THEN 'Mainly clear'
        WHEN 2 THEN 'Partly cloudy'
        WHEN 3 THEN 'Overcast'
        WHEN 45 THEN 'Fog'
        WHEN 48 THEN 'Rime fog'
        WHEN 51 THEN 'Light drizzle'
        WHEN 53 THEN 'Moderate drizzle'
        WHEN 55 THEN 'Dense drizzle'
        WHEN 61 THEN 'Slight rain'
        WHEN 63 THEN 'Moderate rain'
        WHEN 65 THEN 'Heavy rain'
        WHEN 71 THEN 'Slight snow'
        WHEN 73 THEN 'Moderate snow'
        WHEN 75 THEN 'Heavy snow'
        WHEN 80 THEN 'Rain showers'
        WHEN 81 THEN 'Moderate rain showers'
        WHEN 82 THEN 'Violent rain showers'
        WHEN 95 THEN 'Thunderstorm'
        WHEN 96 THEN 'Thunderstorm with hail'
        WHEN 99 THEN 'Severe thunderstorm'
        ELSE 'Unknown'
    END AS WEATHER_DESCRIPTION
FROM RAW.CITY_WEATHER
ORDER BY CITY, DATE DESC;

-- ---------------------------------------------------------------------------
-- 7. Inspect recent weather for a specific city
-- ---------------------------------------------------------------------------
SELECT
    CITY,
    DATE,
    TEMP_MAX,
    TEMP_MIN,
    TEMP_MEAN,
    PRECIPITATION_MM,
    WIND_SPEED_MAX_KMH,
    WEATHER_CODE
FROM RAW.CITY_WEATHER
WHERE CITY = 'Newport Beach'
ORDER BY DATE DESC
LIMIT 5;

-- ---------------------------------------------------------------------------
-- 8. Duplicate record check (should be zero due to PK constraint)
-- ---------------------------------------------------------------------------
SELECT CITY, DATE, COUNT(*)
FROM RAW.CITY_WEATHER
GROUP BY CITY, DATE
HAVING COUNT(*) > 1;
